version: "3"
services:
  hybridq-manylinux2010_x86_64:
    image: hybridq-manylinux2010_x86_64
    container_name: hybridq-manylinux2010_x86_64
    build:
      context: ../
      dockerfile: packages/Dockerfile
      args:
        - BASE=manylinux2010_x86_64
  hybridq-manylinux2014_x86_64:
    image: hybridq-manylinux2014_x86_64
    container_name: hybridq-manylinux2014_x86_64
    build:
      context: ../
      dockerfile: packages/Dockerfile
      args:
        - BASE=manylinux2014_x86_64
